<Project Sdk="Godot.NET.Sdk/4.5.1">
  <Import Project="Sts2PathDiscovery.props" />
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>$(Sts2Path)\mods\$(MSBuildProjectName)\$(MSBuildProjectName).xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(Sts2DataDir)/0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="sts2">
      <HintPath>$(Sts2DataDir)/sts2.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="Sts2PathDiscovery.props" />
    <Content Include="SignatureLib\localization\eng\gameplay_ui.json" />
    <Content Include="SignatureLib\localization\eng\settings_ui.json" />
    <Content Include="SignatureLib\localization\zhs\gameplay_ui.json" />
    <Content Include="SignatureLib\localization\zhs\settings_ui.json" />
  </ItemGroup>
</Project>